version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - external

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email ahmednassar@ilearna.com
      -d www.ilearna.com
      --agree-tos --no-eff-email
      --force-renewal"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - external
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:7000

networks:
  external:
    external:
      name: frontend-backend-net