version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:3000"
    networks:
      - external
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:7000

networks:
  external:
    external:
      name: frontend-backend-net