name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ahmednassar855/ilearna-frontend:latest .
          docker push ahmednassar855/ilearna-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}    
          envs: DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
              set -e
              cd /opt/frontend
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker-compose down
              docker pull ahmednassar855/ilearna-frontend
              docker-compose up -d
              docker rmi $(docker images -f "dangling=true" -q)
